/**:
  ros__parameters:

    # from initialpose (Rviz's 2DPoseEstimate)
    initial_pose_particle_covariance:
      [
        0.0001, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0001, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.0, 0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.0, 0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.0, 0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.001,
      ]
