/**:
  ros__parameters:

    # from initialpose (Rviz's 2DPoseEstimate)
    initial_pose_particle_covariance:
      [
        0.5, 0.0, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.5, 0.0,  0.0,  0.0,  0.0,
        0.0, 0.0, 0.01, 0.0,  0.0,  0.0,
        0.0, 0.0, 0.0,  0.01, 0.0,  0.0,
        0.0, 0.0, 0.0,  0.0,  0.01, 0.0,
        0.0, 0.0, 0.0,  0.0,  0.0,  0.1,
      ]
